# Generated by Django 3.2.5 on 2021-07-12 05:13

from django.db import migrations
from django.contrib.auth.models import Group


def create_user_groups(apps, schema_editor):
    Group.objects.bulk_create([
        Group(name='User'),
        Group(name='Viewer'),
        Group(name='Administrator'),
    ])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user_groups, migrations.RunPython.noop)
    ]
